require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_jobs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SystemJob. As you add validations to SystemJob, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemJob.create! valid_attributes
      get system_jobs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_job = SystemJob.create! valid_attributes
      get system_job_url(system_job)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_job_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      system_job = SystemJob.create! valid_attributes
      get edit_system_job_url(system_job)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemJob" do
        expect {
          post system_jobs_url, params: { system_job: valid_attributes }
        }.to change(SystemJob, :count).by(1)
      end

      it "redirects to the created system_job" do
        post system_jobs_url, params: { system_job: valid_attributes }
        expect(response).to redirect_to(system_job_url(SystemJob.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemJob" do
        expect {
          post system_jobs_url, params: { system_job: invalid_attributes }
        }.to change(SystemJob, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post system_jobs_url, params: { system_job: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_job" do
        system_job = SystemJob.create! valid_attributes
        patch system_job_url(system_job), params: { system_job: new_attributes }
        system_job.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_job" do
        system_job = SystemJob.create! valid_attributes
        patch system_job_url(system_job), params: { system_job: new_attributes }
        system_job.reload
        expect(response).to redirect_to(system_job_url(system_job))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        system_job = SystemJob.create! valid_attributes
        patch system_job_url(system_job), params: { system_job: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_job" do
      system_job = SystemJob.create! valid_attributes
      expect {
        delete system_job_url(system_job)
      }.to change(SystemJob, :count).by(-1)
    end

    it "redirects to the system_jobs list" do
      system_job = SystemJob.create! valid_attributes
      delete system_job_url(system_job)
      expect(response).to redirect_to(system_jobs_url)
    end
  end
end
