# Auto-generated by lightek:domain — registers Catalog in the dashboard nav.
Rails.application.config.after_initialize do
  next unless defined?(DymondDash::FeatureRegistry)
  DymondDash::FeatureRegistry.register do |f|
    f.slug = :catalog; f.label = "Catalog"; f.icon = "box"
    f.gem_source = "catalog"; f.nav_section = :services; f.min_plan = :starter
    f.nav_items = [
      { label: "Catalog", icon: "box", path: "dymond_dash.catalog_dashboard_path" }
    ]
  end
rescue StandardError => e
  Rails.logger.warn "[Catalog] nav registration skipped: #{e.message}"
end
