# Auto-generated by lightek:domain — registers Studio in the dashboard nav.
Rails.application.config.after_initialize do
  next unless defined?(DymondDash::FeatureRegistry)
  DymondDash::FeatureRegistry.register do |f|
    f.slug = :studio; f.label = "Studio"; f.icon = "box"
    f.gem_source = "studio"; f.nav_section = :overview; f.min_plan = :starter
    f.nav_items = [
      { label: "Studio", icon: "box", path: "dymond_dash.studio_dashboard_path" }
    ]
  end
rescue StandardError => e
  Rails.logger.warn "[Studio] nav registration skipped: #{e.message}"
end
