Rails.application.routes.draw do
  resources :departments
  resources :system_jobs
  resources :job_items
  resources :channels
  resources :shows
  resources :episodes
  resources :nevaehs
  resources :profiles
  resources :posts
  resources :communities
  get "/booking", to: "dymond_booking/booking#index"
  mount DymondBooking::Engine => "/booking"
  get "/kb", to: "dymond_kb/kb#index"
  mount DymondKb::Engine => "/kb"
  get "/catalog", to: "dymond_catalog/catalog#index"
  mount DymondCatalog::Engine => "/catalog"
  get "/studio", to: "dymond_studio/studio#index"
  mount DymondStudio::Engine => "/studio"
  resource :session
  resources :passwords, param: :token
  resources :storyline_world_communities
  resources :storyline_world_forges
  resources :storyline_arenas
  resources :storylines
  #resources :dashboards
  resources :supports, only: %i[index create] do
    member { patch :reply }
  end
  resources :stores
  resources :architectures
  resources :abouts
  resources :resellers
  resources :catalogs
  resources :homes
  
# ── Public site ──────────────────────────────────────────────────────────────
root "pages#home"

get  "about",    to: "pages#about"
get  "services", to: "pages#services"
get  "pricing",  to: "pages#pricing"
get  "contact",  to: "pages#contact"


get  "/susu/signup", to: "susu_registrations#new", as: :susu_signup
post "/susu/signup", to: "susu_registrations#create"
get  "/susu/invitations/:token/accept", to: "susu_invitations#accept", as: :accept_susu_invitation

# ── Susu public product surface ───────────────────────────────────────────────
get "susu",            to: "susu_public#home",       as: :susu
get "susu/pricing",    to: "susu_public#pricing",    as: :susu_pricing
get "susu/onboarding", to: "susu_public#onboarding", as: :susu_onboarding

# ── Gatekeeper ──────────────────────────────────────────────────────────────
#Gatekeeper webhook for Stripe
#https://lightekmcg.com/gatekeeper/webhooks/stripe
post "gatekeeper/webhooks/stripe",
     to: "gatekeeper#stripe_webhook",
     as: :gatekeeper_stripe_webhook

post "/susu_groups/:id/request_payout", to: "susu_groups#request_payout", as: :request_payout_susu_group

resources :susu_match_preferences, only: %i[index new create show destroy]


# ── Gatekeeper Infrastructure Control ────────────────────────────────────────
namespace :gatekeeper do
  post "callbacks/github_deployment", to: "callbacks#github_deployment", as: :github_deployment_callback
  get "infrastructure", to: "infrastructure#index", as: :infrastructure
  resources :nodes
  resources :projects do
    member do
      post :deploy
      post :deploy_github
      post :healthcheck
    end
  end
end

# ── Susu ───────────────────────────────────────────────────────
resources :susu_groups do
  member do
    post :activate
    post :request_exit
    get  :contribution
    post :contribute
  end

  resources :susu_memberships, only: %i[create update destroy]
end

# ── Rails 8 native auth ───────────────────────────────────────────────────────
# Generated by: rails generate authentication
resources :sessions,      only: %i[new create destroy]
resources :registrations, only: %i[new create]
get  "sign_in",  to: "sessions#new",      as: :sign_in
get  "sign_up",  to: "registrations#new", as: :sign_up
delete "sign_out", to: "sessions#destroy", as: :sign_out

# ── Client portal ──────────────────────────────────────────────────────────────
namespace :portal do
  root "dashboard#index"
  resources :projects, only: %i[index show new create]
  resources :deliverables, only: %i[index show]
  resources :messages, only: %i[index create]
  resources :services, only: %i[index]
end

# ── Employee portal ────────────────────────────────────────────────────────────
namespace :employee do
    resources :users, only: %i[index new create edit update destroy]
    resources :tickets, only: %i[index show new create] do
      member { patch :reply; patch :resolve }
    end
  root "dashboard#index"
  resources :clients,   only: %i[index show]
  resources :projects,  only: %i[index show edit update]
  resources :timesheets, only: %i[index create]
end

# ── Video Networking System ──────────────────────────────────────────────
get "kitchen_sink",
    to: "kitchen_sink#index",
    defaults: { format: :json },
    as: :kitchen_sink

# ── Video Networking System config feed ──────────────────────────────────────────────
get "kitchen_config",
    to: "kitchen_sink#platform_config",
    defaults: { format: :json },
    as: :kitchen_config

# ── Video Networking System content feed ──────────────────────────────────────────────
get "roku/content/:id",
    to: "kitchen_sink#content",
    defaults: { format: :json },
    as: :roku_content

    # ── Video Networking System Live feed ──────────────────────────────────────────────
    get "roku/screens/live",
    to: "kitchen_sink#live",
    defaults: { format: :json },
    as: :roku_live

    # ── Video Networking System search feed ──────────────────────────────────────────────
    get "roku/search",
    to: "kitchen_sink#search",
    defaults: { format: :json },
    as: :roku_search

    # ── Community preview ──────────────────────────────────────────────
    
    get "preview/community", 
        to: "community_preview#index"

    get "preview/community/topic",
        to: "community_preview#topic"

    get "preview/community/discussion",
        to: "community_preview#discussion"

    get "preview/community/new",
        to: "community_preview#new"

    get "preview/community/profile",
        to: "community_preview#profile"

    get "preview/community/admin",
        to: "community_preview#admin"


# ── Dymond CMS engine — main admin/ops dashboard ──────────────────────────────
  # Lightek human control plane
  get "/dashboard/infrastructure",
      to: "dashboard/infrastructure#index",
      as: :dashboard_infrastructure

  get "/dashboard/susu",
      to: "dashboard/susu#index",
      as: :dashboard_susu

post "/dashboard/susu/payout-account/connect", to: "susu_payout_accounts#connect", as: :connect_dashboard_susu_payout_account
get "/dashboard/susu/payout-account/refresh", to: "susu_payout_accounts#refresh", as: :refresh_dashboard_susu_payout_account
get "/dashboard/susu/payout-account", to: "susu_payout_accounts#show", as: :dashboard_susu_payout_account

mount DymondDash::Engine => "/dashboard"

# ── DymondBank — billing, invoices, subscriptions ─────────────────────────────
mount DymondBank::Engine => "/billing"

# Uncomment as gems are added:
# mount DymondSocial::Engine  => "/social"
# mount LightekStudio::Engine => "/studio"
# mount DymondConnect::Engine => "/connect"

# ── Health check (Kamal / load balancer) ──────────────────────────────────────
get "up", to: "rails/health#show", as: :rails_health_check

# ── PWA ───────────────────────────────────────────────────────────────────────
get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
get "manifest"       => "rails/pwa#manifest",       as: :pwa_manifest


end
