Rails.application.routes.draw do
  get "/kb", to: "dymond_kb/kb#index"
  mount DymondKb::Engine => "/kb"
  get "/catalog", to: "dymond_catalog/catalog#index"
  mount DymondCatalog::Engine => "/catalog"
  get "/studio", to: "dymond_studio/studio#index"
  mount DymondStudio::Engine => "/studio"
  resource :session
  resources :passwords, param: :token
  resources :storyline_world_communities
  resources :storyline_world_forges
  resources :storyline_arenas
  resources :storylines
  #resources :dashboards
  resources :supports, only: %i[index create] do
    member { patch :reply }
  end
  resources :stores
  resources :architectures
  resources :abouts
  resources :resellers
  resources :catalogs
  resources :homes
  
# ── Public site ──────────────────────────────────────────────────────────────
root "pages#home"

get  "about",    to: "pages#about"
get  "services", to: "pages#services"
get  "pricing",  to: "pages#pricing"
get  "contact",  to: "pages#contact"

# ── Rails 8 native auth ───────────────────────────────────────────────────────
# Generated by: rails generate authentication
resources :sessions,      only: %i[new create destroy]
resources :registrations, only: %i[new create]
get  "sign_in",  to: "sessions#new",      as: :sign_in
get  "sign_up",  to: "registrations#new", as: :sign_up
delete "sign_out", to: "sessions#destroy", as: :sign_out

# ── Client portal ──────────────────────────────────────────────────────────────
namespace :portal do
  root "dashboard#index"
  resources :projects, only: %i[index show new create]
  resources :deliverables, only: %i[index show]
  resources :messages, only: %i[index create]
  resources :services, only: %i[index]
end

# ── Employee portal ────────────────────────────────────────────────────────────
namespace :employee do
    resources :users, only: %i[index new create edit update destroy]
    resources :tickets, only: %i[index show new create] do
      member { patch :reply; patch :resolve }
    end
  root "dashboard#index"
  resources :clients,   only: %i[index show]
  resources :projects,  only: %i[index show edit update]
  resources :timesheets, only: %i[index create]
end

# ── Dymond CMS engine — main admin/ops dashboard ──────────────────────────────
mount DymondDash::Engine => "/dashboard"

# ── DymondBank — billing, invoices, subscriptions ─────────────────────────────
mount DymondBank::Engine => "/billing"

# Uncomment as gems are added:
# mount DymondSocial::Engine  => "/social"
# mount LightekStudio::Engine => "/studio"
# mount DymondConnect::Engine => "/connect"

# ── Health check (Kamal / load balancer) ──────────────────────────────────────
get "up", to: "rails/health#show", as: :rails_health_check

# ── PWA ───────────────────────────────────────────────────────────────────────
get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
get "manifest"       => "rails/pwa#manifest",       as: :pwa_manifest


end
