# frozen_string_literal: true
# This migration comes from dymond_bank (originally 20260514000002)
# Generated by: rails generate dymond_bank:install

class CreateDymondBankTables < ActiveRecord::Migration[7.2]
  def change

    # ── Accounts ───────────────────────────────────────────────────────────────
    create_table :dymond_bank_accounts do |t|
      t.string  :accountable_type, null: false
      t.bigint  :accountable_id,   null: false
      t.string  :account_type,     null: false, default: "checking"
      t.string  :status,           null: false, default: "active"
      t.string  :currency,         null: false, default: "usd"
      t.bigint  :balance_cents,    null: false, default: 0
      t.bigint  :available_cents,  null: false, default: 0
      t.bigint  :credit_limit_cents
      t.string  :display_name
      t.timestamps
    end
    add_index :dymond_bank_accounts, %i[accountable_type accountable_id]

    # ── Linked bank accounts (Plaid) ───────────────────────────────────────────
    create_table :dymond_bank_linked_accounts do |t|
      t.string  :linkable_type,        null: false
      t.bigint  :linkable_id,          null: false
      t.string  :processor,            null: false, default: "plaid"
      t.string  :access_token,         null: false   # encrypt at rest in host app
      t.string  :processor_account_id, null: false
      t.string  :plaid_item_id
      t.string  :routing_number
      t.string  :account_last4
      t.string  :account_subtype                     # "checking", "savings"
      t.string  :institution_name
      t.string  :display_name
      t.string  :status,               null: false, default: "pending"
      t.boolean :is_default,           default: false
      t.timestamps
    end
    add_index :dymond_bank_linked_accounts, %i[linkable_type linkable_id]
    add_index :dymond_bank_linked_accounts, :plaid_item_id
    add_index :dymond_bank_linked_accounts, :status

    # ── Ledger entries ─────────────────────────────────────────────────────────
    create_table :dymond_bank_ledger_entries do |t|
      t.references :account,       null: false, foreign_key: { to_table: :dymond_bank_accounts }
      t.string  :direction,        null: false
      t.bigint  :amount_cents,     null: false
      t.string  :currency,         null: false, default: "usd"
      t.string  :memo
      t.string  :reference
      t.bigint  :running_balance_cents
      t.timestamps
    end
    add_index :dymond_bank_ledger_entries, :reference

    # ── Subscription plans ─────────────────────────────────────────────────────
    create_table :dymond_bank_subscription_plans do |t|
      t.string  :slug,                 null: false
      t.string  :name,                 null: false
      t.text    :description
      t.bigint  :price_monthly_cents,  null: false, default: 0
      t.bigint  :price_annual_cents,   null: false, default: 0
      t.string  :currency,             null: false, default: "usd"
      t.boolean :active,               default: true
      t.integer :sort_order,           default: 0
      t.jsonb   :features_json
      t.timestamps
    end
    add_index :dymond_bank_subscription_plans, :slug, unique: true

    # ── Subscriptions ──────────────────────────────────────────────────────────
    create_table :dymond_bank_subscriptions do |t|
      t.string  :subscriber_type,    null: false
      t.bigint  :subscriber_id,      null: false
      t.references :plan,            null: false, foreign_key: { to_table: :dymond_bank_subscription_plans }
      t.references :linked_account,  foreign_key: { to_table: :dymond_bank_linked_accounts }
      t.string  :status,             null: false, default: "trialing"
      t.string  :billing_interval,   null: false, default: "monthly"
      t.string  :processor_ref                     # external subscription ID if any
      t.datetime :trial_ends_at
      t.datetime :current_period_start
      t.datetime :current_period_end
      t.datetime :canceled_at
      t.timestamps
    end
    add_index :dymond_bank_subscriptions, %i[subscriber_type subscriber_id]

    # ── Invoices ───────────────────────────────────────────────────────────────
    create_table :dymond_bank_invoices do |t|
      t.string  :billable_type,          null: false
      t.bigint  :billable_id,            null: false
      t.references :linked_account,      foreign_key: { to_table: :dymond_bank_linked_accounts }
      t.string  :number
      t.string  :status,                 null: false, default: "draft"
      t.string  :invoice_type,           null: false, default: "manual"
      t.string  :currency,               null: false, default: "usd"
      t.bigint  :subtotal_cents,         null: false, default: 0
      t.bigint  :tax_cents,              null: false, default: 0
      t.bigint  :discount_cents,         null: false, default: 0
      t.bigint  :total_cents,            null: false, default: 0
      t.bigint  :amount_paid_cents,      null: false, default: 0
      t.bigint  :amount_remaining_cents, null: false, default: 0
      t.bigint  :platform_fee_cents,     null: false, default: 0
      t.text    :memo
      t.date    :due_date
      t.datetime :finalized_at
      t.datetime :paid_at
      t.timestamps
    end
    add_index :dymond_bank_invoices, %i[billable_type billable_id]
    add_index :dymond_bank_invoices, :number,   unique: true, where: "number IS NOT NULL"
    add_index :dymond_bank_invoices, :status
    add_index :dymond_bank_invoices, :due_date

    # ── Invoice line items ─────────────────────────────────────────────────────
    create_table :dymond_bank_invoice_line_items do |t|
      t.references :invoice,       null: false, foreign_key: { to_table: :dymond_bank_invoices }
      t.string  :description,      null: false
      t.integer :quantity,         null: false, default: 1
      t.bigint  :unit_price_cents, null: false
      t.string  :currency,         null: false, default: "usd"
      t.string  :item_type
      t.string  :reference_id
      t.timestamps
    end

    # ── Transactions ───────────────────────────────────────────────────────────
    create_table :dymond_bank_transactions do |t|
      t.references :account, foreign_key: { to_table: :dymond_bank_accounts }
      t.references :invoice, foreign_key: { to_table: :dymond_bank_invoices }
      t.string  :transaction_type, null: false
      t.string  :status,           null: false, default: "pending"
      t.string  :currency,         null: false, default: "usd"
      t.bigint  :amount_cents,     null: false
      t.bigint  :fee_cents,        null: false, default: 0
      t.bigint  :net_cents,        null: false, default: 0
      t.string  :processor_name                  # "plaid", "manual"
      t.string  :processor_ref                   # Plaid transfer_id or manual ref
      t.string  :idempotency_key
      t.text    :failure_message
      t.timestamps
    end
    add_index :dymond_bank_transactions, :status
    add_index :dymond_bank_transactions, :processor_ref
    add_index :dymond_bank_transactions, :idempotency_key, unique: true, where: "idempotency_key IS NOT NULL"

    # ── Payouts ────────────────────────────────────────────────────────────────
    create_table :dymond_bank_payouts do |t|
      t.string  :recipient_type, null: false
      t.bigint  :recipient_id,   null: false
      t.references :account,     foreign_key: { to_table: :dymond_bank_accounts }
      t.references :linked_account, foreign_key: { to_table: :dymond_bank_linked_accounts }
      t.string  :status,         null: false, default: "pending"
      t.string  :currency,       null: false, default: "usd"
      t.bigint  :amount_cents,   null: false
      t.bigint  :fee_cents,      null: false, default: 0
      t.string  :description
      t.string  :processor_ref                   # Plaid transfer_id
      t.datetime :paid_at
      t.timestamps
    end
    add_index :dymond_bank_payouts, %i[recipient_type recipient_id]
    add_index :dymond_bank_payouts, :status

    # ── Royalty splits ─────────────────────────────────────────────────────────
    create_table :dymond_bank_royalty_splits do |t|
      t.string  :splittable_type, null: false
      t.bigint  :splittable_id,   null: false
      t.string  :recipient_type,  null: false
      t.bigint  :recipient_id,    null: false
      t.decimal :percentage,      null: false, precision: 5, scale: 2
      t.boolean :active,          default: true
      t.string  :label
      t.timestamps
    end
    add_index :dymond_bank_royalty_splits, %i[splittable_type splittable_id]

    # ── Royalty payments ───────────────────────────────────────────────────────
    create_table :dymond_bank_royalty_payments do |t|
      t.references :royalty_split,      null: false, foreign_key: { to_table: :dymond_bank_royalty_splits }
      t.references :source_transaction, null: false, foreign_key: { to_table: :dymond_bank_transactions }
      t.references :payout,             foreign_key: { to_table: :dymond_bank_payouts }
      t.string  :currency,              null: false, default: "usd"
      t.bigint  :gross_cents,           null: false
      t.bigint  :net_cents,             null: false
      t.bigint  :fee_cents,             null: false, default: 0
      t.string  :status,                null: false, default: "pending"
      t.timestamps
    end

    # ── Usage rates ────────────────────────────────────────────────────────────
    create_table :dymond_bank_usage_rates do |t|
      t.string  :meter,               null: false
      t.string  :plan_slug,           null: false, default: "starter"
      t.bigint  :rate_per_unit_cents, null: false, default: 0
      t.string  :currency,            null: false, default: "usd"
      t.string  :unit_label
      t.timestamps
    end
    add_index :dymond_bank_usage_rates, %i[meter plan_slug], unique: true

    # ── Usage records ──────────────────────────────────────────────────────────
    create_table :dymond_bank_usage_records do |t|
      t.string  :metered_type,       null: false
      t.bigint  :metered_id,         null: false
      t.bigint  :usage_charge_id
      t.string  :meter,              null: false
      t.decimal :quantity,           null: false, precision: 12, scale: 4
      t.string  :source_reference
      t.boolean :billed,             default: false
      t.datetime :occurred_at,       null: false
      t.timestamps
    end
    add_index :dymond_bank_usage_records, %i[metered_type metered_id]
    add_index :dymond_bank_usage_records, :billed
    add_index :dymond_bank_usage_records, :meter

    # ── Usage charges ──────────────────────────────────────────────────────────
    create_table :dymond_bank_usage_charges do |t|
      t.string  :chargeable_type,    null: false
      t.bigint  :chargeable_id,      null: false
      t.bigint  :invoice_id
      t.string  :meter,              null: false
      t.decimal :total_quantity,     null: false, precision: 12, scale: 4
      t.bigint  :total_cents,        null: false
      t.string  :currency,           null: false, default: "usd"
      t.date    :period_start
      t.date    :period_end
      t.timestamps
    end
    add_index :dymond_bank_usage_charges, %i[chargeable_type chargeable_id]

    # ── Credit lines ───────────────────────────────────────────────────────────
    create_table :dymond_bank_credit_lines do |t|
      t.string  :borrower_type,  null: false
      t.bigint  :borrower_id,    null: false
      t.string  :status,         null: false, default: "pending"
      t.string  :currency,       null: false, default: "usd"
      t.bigint  :limit_cents,    null: false
      t.bigint  :drawn_cents,    null: false, default: 0
      t.decimal :interest_rate,  precision: 5, scale: 4, default: 0
      t.date    :approved_at
      t.date    :expires_at
      t.timestamps
    end
    add_index :dymond_bank_credit_lines, %i[borrower_type borrower_id]

    # ── Revenue events ─────────────────────────────────────────────────────────
    create_table :dymond_bank_revenue_events do |t|
      t.string  :subject_type,    null: false
      t.bigint  :subject_id,      null: false
      t.string  :event_type,      null: false
      t.string  :status,          null: false, default: "open"
      t.bigint  :potential_cents, default: 0
      t.string  :currency,        null: false, default: "usd"
      t.text    :description
      t.jsonb   :metadata_json
      t.datetime :actioned_at
      t.timestamps
    end
    add_index :dymond_bank_revenue_events, %i[subject_type subject_id]
    add_index :dymond_bank_revenue_events, :event_type
    add_index :dymond_bank_revenue_events, :status

  end
end
