class ApplicationController < ActionController::Base
  skip_authorization_check
  #allow_browser versions: :modern
  # ── Rails 8 native auth helpers ───────────────────────────────────────────────
  include Lightek::Gatekeeper
  include Authentication   # generated by: rails generate authentication
  include NetworkController #handles all of network traffic, has additional listner added
  
  protect_from_forgery with: :null_session, if: -> { request.format.json? }

  # ── Nevaeh ─────────────────────────────────────────────────────────────────
  def start_awareness
  end
  
  # ── CanCanCan ─────────────────────────────────────────────────────────────────
  check_authorization unless: :skip_authorization?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_path, alert: exception.message }
      format.json { render json: { error: exception.message }, status: :forbidden }
    end
  end

  # ── DymondDash helpers — exposed to engine controllers ────────────────────────
  # The DymondDash engine calls main_app.current_user via this method
  helper_method :current_user

  def current_user
    Current.session&.user
  end
  helper_method :current_user

  # Catch Rails strong parameter missing errors globally
  rescue_from ActionController::ParameterMissing, with: :handle_parameter_missing
  
    private

  def handle_parameter_missing(exception)
    render json: { 
      error: "Malconfigured or missing payload", 
      details: exception.message ,
     status: :unprocessable_entity
     }
  end
  

  def skip_authorization?
    devise_controller? rescue false
  end
end
