#!/usr/bin/env bash
set -euo pipefail

# Build the bare-metal Rails production env from the existing working deployment.
#
# Sources, in order of preference:
#   1. Existing /etc/lightek/lightekmcg-site.env
#   2. Repo .env
#   3. Existing Docker web container environment
#
# Bare-metal connection addresses are then forced to localhost.
#
# Run as root from anywhere:
#   bash lib/scripts/build_baremetal_env.sh
#
# Optional:
#   APP_ROOT=/root/apps/lightekmcg-site
#   TARGET_ENV=/etc/lightek/lightekmcg-site.env
#   APP_USER=lightek

[[ "${EUID}" -eq 0 ]] || {
  echo "ERROR: run as root."
  exit 1
}

APP_ROOT="${APP_ROOT:-/root/apps/lightekmcg-site}"
TARGET_ENV="${TARGET_ENV:-/etc/lightek/lightekmcg-site.env}"
APP_USER="${APP_USER:-lightek}"
SOURCE_ENV="${APP_ROOT}/.env"

mkdir -p "$(dirname "${TARGET_ENV}")"

declare -A VALUES

# Load KEY=VALUE files without executing them.
load_env_file() {
  local file="$1"
  [[ -f "$file" ]] || return 0

  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" != *=* ]] && continue

    local key="${line%%=*}"
    local value="${line#*=}"

    key="$(printf '%s' "$key" | xargs)"
    [[ -z "$key" ]] && continue

    # Strip one matching pair of outer quotes only.
    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value:1:${#value}-2}"
    fi

    VALUES["$key"]="$value"
  done < "$file"
}

# Lowest-priority source first.
load_docker_env() {
  command -v docker >/dev/null 2>&1 || return 0

  local container=""
  container="$(docker ps -a \
    --filter "name=lightekmcg-site-web" \
    --format '{{.Names}}' \
    | head -1 || true)"

  [[ -n "$container" ]] || return 0

  while IFS= read -r pair; do
    [[ "$pair" != *=* ]] && continue
    local key="${pair%%=*}"
    local value="${pair#*=}"

    # Only seed missing values from Docker.
    if [[ -z "${VALUES[$key]+x}" || -z "${VALUES[$key]}" ]]; then
      VALUES["$key"]="$value"
    fi
  done < <(docker inspect "$container" \
    --format '{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null || true)
}

# Start with Docker as fallback, then repo .env, then existing target env.
load_docker_env
load_env_file "$SOURCE_ENV"
load_env_file "$TARGET_ENV"

# Map current Docker/app naming into the bare-metal environment.
if [[ -n "${VALUES[DB_HOST]:-}" && -z "${VALUES[POSTGRES_HOST]:-}" ]]; then
  VALUES[POSTGRES_HOST]="${VALUES[DB_HOST]}"
fi

if [[ -n "${VALUES[INGRESS_PASSWORD]:-}" && -z "${VALUES[RAILS_INBOUND_EMAIL_PASSWORD]:-}" ]]; then
  VALUES[RAILS_INBOUND_EMAIL_PASSWORD]="${VALUES[INGRESS_PASSWORD]}"
fi

# Force host-side service addresses.
VALUES[POSTGRES_HOST]="127.0.0.1"
VALUES[POSTGRES_PORT]="5432"
VALUES[REDIS_URL]="redis://127.0.0.1:6379/0"
VALUES[MINIO_ENDPOINT]="http://127.0.0.1:9000"

# Production runtime values.
VALUES[RAILS_ENV]="production"
VALUES[RACK_ENV]="production"
VALUES[RAILS_SERVE_STATIC_FILES]="true"

# Keep the actual production DB name/user already in use.
# If absent, use the values we've already established for this deployment.
: "${VALUES[POSTGRES_DB]:=lightekmcg_production}"
: "${VALUES[POSTGRES_USER]:=lightek}"

KEYS=(
  RAILS_ENV
  RACK_ENV
  RAILS_SERVE_STATIC_FILES

  SECRET_KEY_BASE
  RAILS_MASTER_KEY
  LOCKBOX_MASTER_KEY
  RAILS_INBOUND_EMAIL_PASSWORD

  POSTGRES_HOST
  POSTGRES_PORT
  POSTGRES_DB
  POSTGRES_USER
  POSTGRES_PASSWORD

  REDIS_URL

  MINIO_ENDPOINT
  MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD
  MINIO_BUCKETS

  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
)

escape_env_value() {
  # Quote every value safely for EnvironmentFile/source usage.
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by build_baremetal_env.sh"
  echo "# $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo

  for key in "${KEYS[@]}"; do
    value="${VALUES[$key]:-}"
    [[ -z "$value" ]] && continue
    printf '%s=' "$key"
    escape_env_value "$value"
    printf '\n'
  done
} > "$TMP"

install -o root -g "$APP_USER" -m 0640 "$TMP" "$TARGET_ENV"

echo "Bare-metal environment written:"
echo "  $TARGET_ENV"
echo

echo "=== STATUS (secrets hidden) ==="
for key in "${KEYS[@]}"; do
  if [[ -n "${VALUES[$key]:-}" ]]; then
    printf '%-32s PRESENT\n' "$key"
  else
    printf '%-32s MISSING\n' "$key"
  fi
done

echo
echo "=== CORE CONNECTIVITY VALUES ==="
echo "POSTGRES_HOST=127.0.0.1"
echo "POSTGRES_PORT=5432"
echo "POSTGRES_DB=${VALUES[POSTGRES_DB]}"
echo "POSTGRES_USER=${VALUES[POSTGRES_USER]}"
echo "REDIS_URL=redis://127.0.0.1:6379/0"
echo "MINIO_ENDPOINT=http://127.0.0.1:9000"
echo

required=(
  POSTGRES_PASSWORD
  SECRET_KEY_BASE
  MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD
)

missing=0
for key in "${required[@]}"; do
  if [[ -z "${VALUES[$key]:-}" ]]; then
    echo "REQUIRED VALUE MISSING: $key"
    missing=1
  fi
done

if [[ "$missing" -eq 1 ]]; then
  echo
  echo "The file was created, but one or more required values could not be recovered"
  echo "from the current repo env, existing target env, or Docker container."
  exit 2
fi

echo "Core production values recovered successfully."
echo "No secrets were printed."
